/* SVG viewports frame the supplied product renders without altering the designs. */
const art = {
 metal:['products/fluid-metal-front.webp',1010,2098,0,0,1010,2098], metalSide:['products/fluid-metal-side.webp',191,2098,0,0,191,2098], metalBack:['products/fluid-metal-back.webp',1015,2083,0,0,1015,2083],
 crystal:['products/crystal-inlay-front.webp',1062,2144,0,0,1062,2144], crystalSide:['products/crystal-inlay-side.webp',233,2142,0,0,233,2142], crystalBack:['products/crystal-inlay-back.webp',1097,2136,0,0,1097,2136],
 cherry:['products/cherry-jelly-front.webp',1087,2115,0,0,1087,2115], cherrySide:['products/cherry-jelly-side.webp',281,2128,0,0,281,2128], cherryBack:['products/cherry-jelly-back.webp',1067,2121,0,0,1067,2121],
 blue:['products/blue-jelly-front.webp',1087,2115,0,0,1087,2115], blueSide:['products/blue-jelly-side.webp',282,2126,0,0,282,2126], blueBack:['products/blue-jelly-back.webp',1067,2120,0,0,1067,2120],
 cheese:['products/cheese-character-front.webp',1082,2110,0,0,1082,2110], cheeseSide:['products/cheese-character-side.webp',233,2135,0,0,233,2135], cheeseBack:['products/cheese-character-back.webp',1016,2127,0,0,1016,2127],
 cutout:['products/cheese-cutout-front.webp',1349,2142,0,0,1349,2142], cutoutSide:['products/cheese-cutout-side.webp',241,2135,0,0,241,2135], cutoutBack:['products/cheese-cutout-back.webp',1122,2112,0,0,1122,2112]
};
const products = [
 {id:'fluid-metal',name:'Fluid Metal',series:'sculptural',category:'cases',image:'metal',alternate:'metalBack',images:['metal','metalSide','metalBack'],colors:['Silver / White'],colorImages:['metal'],description:'An open, sculptural surface. Organic lines and metallic contrasts turn the phone case into a small architectural object.',detail:'The concept pairs a flexible case shell with a metallic-finish decorative overlay. Final materials and specifications will be confirmed at release.'},
 {id:'crystal-inlay',name:'Crystal Inlay',series:'sculptural',category:'cases',image:'crystal',alternate:'crystalBack',images:['crystal','crystalSide','crystalBack'],colors:['Silver / White'],colorImages:['crystal'],description:'A stone-like silhouette, interrupted by luminous windows. An exploration of translucent detail and organic form.',detail:'Translucent inlays and a sculpted outer shell are shown in the concept artwork. Final materials will be confirmed at release.'},
 {id:'cherry-jelly',name:'Cherry Jelly',series:'playful',category:'cases',image:'cherry',alternate:'cherryBack',images:['cherry','cherrySide','cherryBack'],colors:['Cherry / Pink'],colorImages:['cherry'],description:'A little dessert, a lot of personality. Cherry-red jelly details meet a soft pink silhouette.',detail:'A dessert-inspired character with raised jelly-shaped details. Product images show the design concept.'},
 {id:'blue-jelly',name:'Blue Jelly',series:'playful',category:'cases',image:'blue',alternate:'blueBack',images:['blue','blueSide','blueBack'],colors:['Jelly Blue'],colorImages:['blue'],description:'The jelly character in a cooler mood. Translucent blue details and a playful expression.',detail:'A blue variation of the jelly character concept, with a coordinated pale-blue shell.'},
 {id:'cheese-character',name:'Cheese Character',series:'playful',category:'cases',image:'cheese',alternate:'cheeseBack',images:['cheese','cheeseSide','cheeseBack'],colors:['Cheese Yellow'],colorImages:['cheese'],description:'A familiar shape with an unexpected face. Playful holes, expressive eyes and a distinctly cheesy character.',detail:'The concept explores a textured surface and raised facial details. Final construction will be confirmed at release.'},
 {id:'cheese-cutout',name:'Cheese Cutout Case',series:'accessories',category:'cases',image:'cutout',alternate:'cutoutBack',images:['cutout','cutoutSide','cutoutBack'],colors:['Cheese Yellow'],colorImages:['cutout'],description:'Holes, curves and a bright yellow finish. The cheese motif, pared back to its simplest expression.',detail:'Part of the extended cheese collection shown in the design study. Final fit and construction will be confirmed at release.'}
].map(p=>({...p,price:29.90}));
const comingSoonIds=new Set(['crystal-inlay','cherry-jelly','blue-jelly','cheese-character','cheese-cutout']);
const money = n => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',currencyDisplay:'code'}).format(n);
const main=document.querySelector('main'), drawer=document.querySelector('#drawer'), drawerContent=document.querySelector('#drawer-content');
let saved=[];try{saved=JSON.parse(localStorage.getItem('zozo-saved')||'[]');if(!Array.isArray(saved))saved=[];saved=saved.filter(id=>products.some(p=>p.id===id));}catch{saved=[];}
let imageSequence=0;
let filterCategory='all',sortOrder='editorial',largeGrid=false,activeSeries='all',returnFocus=null,toastTimer;
function crop(key,alt='',extra='') {
 const [file,canvasW,canvasH,x,y,w,h]=art[key];
 const pad=file.startsWith('products/')?.08:0,viewX=x-w*pad,viewY=y-h*pad,viewW=w*(1+pad*2),viewH=h*(1+pad*2);
 const clip='art-'+(++imageSequence),frost=clip+'-frost';
 const comingSoon=products.some(p=>comingSoonIds.has(p.id)&&[p.image,p.alternate,...p.images,...p.colorImages].includes(key));
 const labelSize=Math.max(11,Math.min(40,viewW/13,viewH*.075)),blur=Math.max(12,Math.min(w,h)*.035);
 return `<svg class="crop art-${key} ${extra}${comingSoon?' coming-soon-art':''}" viewBox="${viewX} ${viewY} ${viewW} ${viewH}" preserveAspectRatio="xMidYMid meet" role="img" aria-label="${alt}${comingSoon?' — Coming soon':''}" xmlns="http://www.w3.org/2000/svg"><defs><clipPath id="${clip}"><rect x="${x}" y="${y}" width="${w}" height="${h}" /></clipPath>${comingSoon?`<filter id="${frost}" x="-20%" y="-20%" width="140%" height="140%"><feGaussianBlur stdDeviation="${blur}" /></filter>`:''}</defs><image href="assets/${file}" width="${canvasW}" height="${canvasH}" clip-path="url(#${clip})"${comingSoon?` filter="url(#${frost})"`:''} />${comingSoon?`<rect x="${viewX}" y="${viewY}" width="${viewW}" height="${viewH}" fill="#fff" fill-opacity=".42" /><text x="${viewX+viewW/2}" y="${viewY+viewH/2}" text-anchor="middle" dominant-baseline="middle" fill="#262626" font-family="Alan, Arial, sans-serif" font-size="${labelSize}" font-weight="600" letter-spacing="${labelSize*.1}">COMING SOON</text>`:''}</svg>`;
}
function saveText(id){return saved.includes(id)?'Saved −':'Save +';}
function card(p){return `<article class="product-card"><a class="visual" href="#/product/${p.id}" aria-label="View ${p.name}">${crop(p.image,p.name+' design preview')}${p.alternate?crop(p.alternate,p.name+' alternate view','alternate'):''}</a><div class="metadata"><h3><a href="#/product/${p.id}">${p.name}</a></h3><span class="status">${money(p.price)}</span></div><button class="save-small" data-save="${p.id}" aria-label="Save ${p.name}" aria-pressed="${saved.includes(p.id)}">${saveText(p.id)}</button></article>`;}
function grid(items){return `<div class="product-grid">${items.map(card).join('')}</div>`;}
function categories(){return `<section class="categories"><h2>Explore the collections</h2><div class="category-grid">${[['sculptural','Sculptural','metal'],['playful','Playful','cherry'],['accessories','Extended objects','cutout']].map(([id,title,key])=>`<a href="#/shop/${id}">${crop(key,title+' collection')}<h3>${title}<span>↗</span></h3></a>`).join('')}</div></section>`;}
function home(){return `<section class="hero"><div class="hero-images hero-solo">${crop('metal','Fluid Metal phone case, silver and white')}</div><div class="hero-caption"><p class="eyebrow">ZOZO Lab / First release</p><h1>Fluid Metal.</h1><a class="text-link" href="#/product/fluid-metal">Explore the design</a></div><span class="hero-index">01 — SCULPTURAL</span></section><div class="intro-line"><span>Phone cases & everyday objects</span><span>The collection / Design preview</span></div><section class="editorial-pair"><div class="left-col"><div class="editorial-copy"><p class="eyebrow">The playful collection</p><h2>A little out<br>of the ordinary.</h2><a class="text-link" href="#/shop/playful">Discover the edit</a></div><a class="image-link" href="#/product/cherry-jelly">${crop('cherry','Cherry Jelly pink phone case')}</a><div class="caption"><span>Cherry Jelly</span><span>${money(29.9)}</span></div></div><div class="right-col"><a class="image-link" href="#/product/blue-jelly">${crop('blue','Blue Jelly phone case')}</a><div class="caption"><span>Blue Jelly</span><span>${money(29.9)}</span></div></div></section><section><div class="section-title"><h2>Objects in focus</h2><a class="text-link" href="#/shop">View all objects</a></div>${grid([products[0],products[1],products[4],products[5]])}</section><section class="campaign"><div class="campaign-photo">${crop('cutout','Cheese Cutout phone case')}</div><div class="campaign-copy"><p class="eyebrow">The extended collection</p><h2>A playful<br>way through.</h2><p>Bold cutouts turn a bright case into a graphic object.</p><a class="text-link" href="#/shop/accessories">Explore the collection</a></div></section>${categories()}<section class="feature">${crop('crystal','Crystal Inlay phone case')}<div class="feature-copy"><p class="eyebrow">Sculptural surfaces</p><h2>Crystal Inlay.</h2><p>Soft contours frame translucent details in a bright, tactile silhouette.</p><a class="text-link" href="#/product/crystal-inlay">Discover the design</a></div></section>`;}
function listing(series){activeSeries=['sculptural','playful','accessories'].includes(series)?series:'all';const titles={all:'All objects.',sculptural:'Sculptural.',playful:'Playful.',accessories:'Extended objects.'};return `<section class="listing"><div class="listing-top"><h1>${titles[activeSeries]}</h1><p>Collection preview<br><span id="result-count"></span></p></div><div class="catalog-tools"><nav class="category-tabs" aria-label="Collections">${[['all','All'],['sculptural','Sculptural'],['playful','Playful'],['accessories','Extended objects']].map(([id,label])=>`<a href="#/shop${id==='all'?'':'/'+id}" aria-current="${id===activeSeries}">${label}</a>`).join('')}</nav><div class="tool-actions"><button id="view-toggle" aria-pressed="${largeGrid}">View: ${largeGrid?'Large':'Grid'}</button><button data-panel="filter">Filter / Sort</button></div></div><div class="product-grid ${largeGrid?'large-grid':''}" id="catalog"></div></section>`;}
function updateCatalog(){const catalog=document.querySelector('#catalog');if(!catalog)return;let items=products.filter(p=>(activeSeries==='all'||p.series===activeSeries)&&(filterCategory==='all'||p.category===filterCategory));if(sortOrder==='az')items.sort((a,b)=>a.name.localeCompare(b.name));if(sortOrder==='za')items.sort((a,b)=>b.name.localeCompare(a.name));catalog.innerHTML=items.length?items.map(card).join(''):`<div class="empty"><h2>No objects in this selection.</h2><p>Try another category or clear your filters.</p><button class="text-link" id="clear-filters">Clear filters</button></div>`;document.querySelector('#result-count').textContent=`${items.length} objects`;}
function productPage(p){return `<section class="detail"><div><div class="gallery" aria-label="${p.name} image gallery" tabindex="0">${p.images.map(key=>crop(key,p.name+' — '+key,'fit')).join('')}</div><p class="gallery-hint">Swipe to explore · ${p.images.length} ${p.images.length===1?'image':'images'}</p></div><div class="detail-info"><a class="back" href="#/shop/${p.series}">← Back to collection</a><p class="eyebrow">${p.series==='accessories'?'Extended objects':p.series} / Design preview</p><h1>${p.name}</h1><p class="price">${money(p.price)}</p><span class="field-label">Shown in <span id="color-name">${p.colors[0]}</span></span><div class="variant-list">${p.colors.map((color,i)=>`<button data-color="${i}" data-product="${p.id}" aria-pressed="${i===0}">${color}</button>`).join('')}</div><span class="field-label">${p.category==='cases'?'Device compatibility':'Compatibility'}</span><p class="device-note">Final ${p.category==='cases'?'device lineup':'fit'} to be announced.</p><button class="outline-button" data-save="${p.id}" aria-pressed="${saved.includes(p.id)}">${saved.includes(p.id)?'Saved to your edit −':'Save to your edit +'}</button><p class="product-description">${p.description}</p><details><summary>Design & details</summary><p>${p.detail}</p></details><details><summary>Availability</summary><p>This collection is being developed. The images show design previews. Online ordering is not open yet.</p></details></div></section><section class="related"><div class="section-title"><h2>Continue exploring</h2><a class="text-link" href="#/shop">All objects</a></div>${grid(products.filter(x=>x.id!==p.id).slice(0,4))}</section>`;}
function collections(){return `<section class="listing"><div class="listing-top"><h1>Two personalities.<br>One point of view.</h1><p>ZOZO Lab<br>Collections</p></div>${categories()}</section>`;}
function about(){return `<section class="about"><p class="eyebrow">About ZOZO Lab</p><h1>Everyday objects.<br>Individual expression.</h1><p>ZOZO Lab explores mobile accessories through sculptural forms, playful characters and unexpected details.</p><p>From a fluid metal surface to a familiar shape with a sense of humor, each design brings a different personality to the things we carry.</p><a class="text-link" href="#/collections">Explore the collections</a>${crop('metal','Fluid Metal design study')}</section>`;}
function render(){if(location.hash==='#main')return;if(drawer.open)drawer.close();const [route,id]=location.hash.replace(/^#\/?/,'').split('/');document.querySelector('.header').classList.toggle('over-hero',!route);let title='Mobile accessories';if(!route){main.innerHTML=home();}else if(route==='shop'){main.innerHTML=listing(id);updateCatalog();title=activeSeries==='all'?'All objects':activeSeries;}else if(route==='collections'){main.innerHTML=collections();title='Collections';}else if(route==='product'){const p=products.find(x=>x.id===id);main.innerHTML=p?productPage(p):`<section class="about"><h1>Object not found.</h1><p><a class="text-link" href="#/shop">Explore all objects</a></p></section>`;title=p?p.name:'Object not found';}else if(route==='about'){main.innerHTML=about();title='About';}else{main.innerHTML=`<section class="about"><h1>Page not found.</h1><p><a class="text-link" href="#/">Return home</a></p></section>`;}document.title=`ZOZO Lab — ${title}`;window.scrollTo(0,0);updateSaved();}
function updateSaved(){document.querySelectorAll('[data-saved-count]').forEach(el=>el.textContent=`[${saved.length}]`);document.querySelectorAll('[data-save]').forEach(el=>{const yes=saved.includes(el.dataset.save);el.setAttribute('aria-pressed',String(yes));el.textContent=el.classList.contains('outline-button')?(yes?'Saved to your edit −':'Save to your edit +'):saveText(el.dataset.save);});}
function toggleSave(id){if(!products.some(p=>p.id===id))return;saved=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];try{localStorage.setItem('zozo-saved',JSON.stringify(saved));}catch{}updateSaved();const toast=document.querySelector('.toast');toast.textContent=saved.includes(id)?'Added to your saved edit':'Removed from your saved edit';toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),2200);if(drawer.open&&drawer.dataset.panel==='saved')savedPanel();}
function miniProduct(p,remove=false){return `<article class="mini-product"><a href="#/product/${p.id}" aria-label="View ${p.name}">${crop(p.image,p.name)}</a><div><a href="#/product/${p.id}">${p.name}</a><p>${money(p.price)}</p>${remove?`<button data-save="${p.id}" aria-label="Remove ${p.name} from saved edit">Remove</button>`:''}</div></article>`;}
function savedPanel(){drawerContent.innerHTML=`<p class="drawer-description">Your personal edit, saved on this device.</p>${saved.length?products.filter(p=>saved.includes(p.id)).map(p=>miniProduct(p,true)).join(''):'<div class="empty"><h3>Your edit starts here.</h3><p>Save the objects that catch your eye.</p><a class="text-link" href="#/shop">Explore all objects</a></div>'}`;}
function searchResults(query=''){const q=query.trim().toLowerCase();const items=products.filter(p=>`${p.name} ${p.series} ${p.colors.join(' ')}`.toLowerCase().includes(q));document.querySelector('.search-results').innerHTML=`<p class="eyebrow" role="status">${items.length} objects</p>${items.length?items.map(p=>miniProduct(p)).join(''):'<p>No matching objects. Try “jelly”, “cheese” or “sculptural”.</p>'}`;}
function openPanel(type){returnFocus=document.activeElement;drawer.dataset.panel=type;const title=document.querySelector('#drawer-title');const titles={menu:'Explore',search:'Search',saved:'Your saved edit',filter:'Filter / Sort',availability:'Collection availability',privacy:'Privacy'};title.textContent=titles[type]||'Information';if(type==='menu'){drawerContent.innerHTML=`<nav class="drawer-nav"><a href="#/shop">All objects</a><a href="#/shop/sculptural">Sculptural</a><a href="#/shop/playful">Playful</a><a href="#/shop/accessories">Extended objects</a><a href="#/collections">Collections</a><a href="#/about" class="small">About ZOZO Lab</a></nav>`;}else if(type==='search'){drawerContent.innerHTML='<label class="field-label" for="search-input">Find an object</label><input class="search-input" id="search-input" type="search" placeholder="Search the collection" autocomplete="off"><div class="search-results"></div>';searchResults();}else if(type==='saved'){savedPanel();}else if(type==='filter'){drawerContent.innerHTML=`<form class="filter-form"><label>Category<select name="category"><option value="all">All objects</option><option value="cases">Phone cases</option><option value="accessories">Accessories</option></select></label><label>Sort<select name="sort"><option value="editorial">Editorial order</option><option value="az">Name: A to Z</option><option value="za">Name: Z to A</option></select></label><button class="outline-button" type="submit">Apply</button><button type="button" id="reset-filter">Reset filters</button></form>`;drawerContent.querySelector('[name=category]').value=filterCategory;drawerContent.querySelector('[name=sort]').value=sortOrder;}else if(type==='availability'){drawerContent.innerHTML='<p class="drawer-description">Explore the collection ahead of release. Product imagery shows design previews; final materials, colors and device compatibility will be confirmed at launch.</p><p>Online ordering is not open yet.</p>';}else if(type==='privacy'){drawerContent.innerHTML='<p class="drawer-description">This website uses Google Analytics to measure visits and engagement. Your saved edit stays in this browser’s local storage.</p><p>This preview does not collect account, payment or newsletter information. You can remove saved objects individually or clear this website’s data in your browser settings.</p>';}if(!drawer.open)drawer.showModal();if(type==='search')drawerContent.querySelector('input').focus();}
document.addEventListener('click',event=>{const button=event.target.closest('button');if(button?.dataset.panel)openPanel(button.dataset.panel);if(button?.dataset.save)toggleSave(button.dataset.save);if(button?.id==='view-toggle'){largeGrid=!largeGrid;document.querySelector('#catalog').classList.toggle('large-grid',largeGrid);button.textContent=`View: ${largeGrid?'Large':'Grid'}`;button.setAttribute('aria-pressed',String(largeGrid));}if(button?.id==='clear-filters'){filterCategory='all';sortOrder='editorial';updateCatalog();}if(button?.id==='reset-filter'){drawerContent.querySelector('[name=category]').value='all';drawerContent.querySelector('[name=sort]').value='editorial';}if(button?.dataset.color!==undefined){const p=products.find(x=>x.id===button.dataset.product),i=Number(button.dataset.color);document.querySelector('.gallery .crop').outerHTML=crop(p.colorImages[i],p.name+' — '+p.colors[i],'fit');document.querySelector('#color-name').textContent=p.colors[i];document.querySelectorAll('[data-color]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));document.querySelector('.gallery').scrollTo({left:0});}if(event.target.closest('a')&&drawer.open)drawer.close();});
drawerContent.addEventListener('input',e=>{if(e.target.id==='search-input')searchResults(e.target.value);});
drawerContent.addEventListener('submit',e=>{if(e.target.matches('.filter-form')){e.preventDefault();filterCategory=e.target.elements.category.value;sortOrder=e.target.elements.sort.value;updateCatalog();drawer.close();}});
document.querySelector('#close-drawer').addEventListener('click',()=>drawer.close());drawer.addEventListener('click',e=>{if(e.target===drawer){const r=drawer.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)drawer.close();}});drawer.addEventListener('close',()=>{if(returnFocus?.isConnected)returnFocus.focus();});
function updateHeader(){document.querySelector('.header').classList.toggle('over-hero',Boolean(document.querySelector('.hero'))&&window.scrollY<40);}
window.addEventListener('scroll',updateHeader,{passive:true});
window.addEventListener('hashchange',()=>{render();updateHeader();if(location.hash!=='#main')main.focus({preventScroll:true});});document.querySelector('#year').textContent=new Date().getFullYear();render();updateHeader();
